In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Реалізація двовимірного дискретного косинусного перетворення

Матриця перетворення для випадку N = 8 :

$$ 
G_u = \sqrt{\frac{2}{N}} \frac{1}{\sqrt{2}} f_0 + 
\sqrt{\frac{2}{N}} \sum_{x=1}^7 f_x \, cos\left( \frac{\pi}{8} (u + \frac{1}{2}) x \right)
$$



Перетворення застосовується наступним чином (ДКП застосовується до кожного стовпця, а потім до кожного рядка):


$$ G = {DCT} \cdot f \cdot {DCT}^{T} $$

In [ ]:
a = np.random.randn(8,8)
np.set_printoptions(precision=3)

In [ ]:
print(a)

[[ 0.919 -1.833 -2.725 -0.755  0.176 -0.669  0.078  0.412]

 [ 1.095  0.596 -0.265 -1.441 -0.176 -0.437  0.137  0.111]

 [ 0.455 -0.864 -0.44  -0.824  2.183  1.124  0.909  0.004]

 [ 0.902 -0.873  0.348  0.323 -1.528  1.263  0.825  1.525]

 [ 0.693  0.996  0.037  2.361 -0.862 -1.163 -1.821 -0.594]

 [-0.079 -0.389  0.623 -1.302  0.959  0.417  1.069 -0.479]

 [-0.423  1.588 -0.957 -0.316  0.395  0.883  0.541 -1.228]

 [-1.153 -1.349  0.629 -0.316 -0.779  0.143 -0.379 -0.042]]


In [ ]:
# транспонирование матрицы
a_transpose = a.transpose()
print(a_transpose)

[[ 0.919  1.095  0.455  0.902  0.693 -0.079 -0.423 -1.153]

 [-1.833  0.596 -0.864 -0.873  0.996 -0.389  1.588 -1.349]

 [-2.725 -0.265 -0.44   0.348  0.037  0.623 -0.957  0.629]

 [-0.755 -1.441 -0.824  0.323  2.361 -1.302 -0.316 -0.316]

 [ 0.176 -0.176  2.183 -1.528 -0.862  0.959  0.395 -0.779]

 [-0.669 -0.437  1.124  1.263 -1.163  0.417  0.883  0.143]

 [ 0.078  0.137  0.909  0.825 -1.821  1.069  0.541 -0.379]

 [ 0.412  0.111  0.004  1.525 -0.594 -0.479 -1.228 -0.042]]


In [ ]:
np.dot()